name: link_dance
description: Rede social de dança
version: 0.2.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.0
  chips_choice_null_safety: ^2.0.6
  getwidget: ^3.0.1
  youtube_player_flutter: ^8.1.0
  intl: 0.17.0
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.4.1
  google_sign_in: ^5.4.1
  firebase_auth: ^4.2.4
  sign_in_with_apple: ^4.1.0
  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
  firebase_storage: ^11.0.10
  sqflite: ^2.0.3+1
  chewie: ^1.3.4
  percent_indicator: ^4.2.2
  path_provider: ^2.0.11
  flutter_custom_clippers: ^2.0.0
  currency_text_input_formatter: ^2.1.7
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  cloud_firestore: ^4.2.0
  timeago: ^3.3.0
  easy_image_viewer: ^1.1.0
  flutter_native_image: ^0.0.6
  dropdown_button2: ^1.8.2
  like_button: ^2.0.5
  video_thumbnail: ^0.5.3
  jwt_decoder: ^2.0.1
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.0
  video_player: ^2.4.8
  firestore_cache: ^2.3.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.7
  splashscreen: ^1.3.5
  flutter_native_splash: ^2.2.16
  firebase_crashlytics: ^3.0.9
  upgrader: ^5.0.0
  package_info_plus: ^3.0.2



flutter_native_splash:
  image: assets/images/splash.jpg


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/login2.json
    - assets/images/large/home.png
    - assets/images/large/home.jpg
    - assets/images/dancando2.png
    - assets/images/dancando3.png
    - assets/images/dancando4.png
    - assets/images/backgroud1.jpg
    - assets/images/backgroud3.jpg
    - assets/images/backgroud4.jpg
    - assets/images/default.jpg
    - assets/images/bebe-dancando.gif
    - assets/images/registration_background.jpg
    - assets/images/perfil.png
    - assets/images/default_teacher.jpg
    - assets/images/drawer_profile_backgroud.png
    - assets/images/drawer_body_backgroud.png
    - assets/images/danca.jpg
    - assets/images/start.jpeg
    - assets/images/default_profile.jpg
    - assets/images/backgroud2.jpg
    - assets/images/logo/logo.jpg
    - assets/images/logo/logo.png
    - assets/images/logo/logo-720.jpg
    - assets/images/logo/logo-720.png
    - assets/images/logo/icon.png
    - assets/images/splash.jpg




  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald/Oswald-SemiBold.ttf
        - asset: assets/fonts/oswald/Oswald-ExtraLight.ttf
        - asset: assets/fonts/oswald/Oswald-Light.ttf
        - asset: assets/fonts/oswald/Oswald-Medium.ttf
        - asset: assets/fonts/oswald/Oswald-Regular.ttf
        - asset: assets/fonts/oswald/Oswald-SemiBold.ttf
